import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "@/context/AuthContext";
import Navbar from "./components/Navbar";
import StyledComponentsRegistry from "@/lib/AntdRegistry";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Trello clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-hidden`}>
        <StyledComponentsRegistry>
          {/* <AuthProvider> */}

          <Navbar />
          {children}
          {/* </AuthProvider> */}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
